export interface ModuleDefinition {
  id: string;
  name: string;
  category: 'Foundation' | 'People' | 'Finance' | 'Admissions' | 'Academics' | 'Students' | 'Intelligence';
  icon: string;
  description: string;
  requiredModules: string[];
  recommendedModules: string[];
  isCore: boolean;
  pricingTier: 'starter' | 'academic' | 'enterprise';
}

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: 'organization',
    name: 'Institution Setup',
    category: 'Foundation',
    icon: '🏫',
    description: 'Campus profiles, org structure, academic calendar, branding and multi-campus management.',
    requiredModules: [],
    recommendedModules: [],
    isCore: true,
    pricingTier: 'starter',
  },
  {
    id: 'compliance',
    name: 'Governance & Compliance',
    category: 'Foundation',
    icon: '🛡️',
    description: 'Policy management, audit trails, risk registers and regulatory compliance tracking.',
    requiredModules: ['organization'],
    recommendedModules: ['documents'],
    isCore: false,
    pricingTier: 'enterprise',
  },
  {
    id: 'documents',
    name: 'Documents & Workflow',
    category: 'Foundation',
    icon: '📋',
    description: 'Digital document management, multi-stage approvals, expiry tracking and e-signatures.',
    requiredModules: ['organization'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'starter',
  },
  {
    id: 'hr',
    name: 'Staff & HR',
    category: 'People',
    icon: '👥',
    description: 'Staff profiles, leave management, payroll processing, CPD tracking and appraisals.',
    requiredModules: ['organization'],
    recommendedModules: ['documents'],
    isCore: false,
    pricingTier: 'starter',
  },
  {
    id: 'teaching',
    name: 'Teaching Management',
    category: 'People',
    icon: '🎓',
    description: 'Lesson plans, classroom observations, CPD logs and teacher performance analytics.',
    requiredModules: ['organization', 'hr'],
    recommendedModules: ['curriculum'],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'finance',
    name: 'Finance',
    category: 'Finance',
    icon: '💰',
    description: 'Fee collection, invoices, budgets, expenses, payroll and full financial reporting.',
    requiredModules: ['organization'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'starter',
  },
  {
    id: 'procurement',
    name: 'Procurement',
    category: 'Finance',
    icon: '🛒',
    description: 'Purchase orders, vendor management, stock tracking and purchase approval workflows.',
    requiredModules: ['organization', 'finance'],
    recommendedModules: ['campus-ops', 'documents'],
    isCore: false,
    pricingTier: 'enterprise',
  },
  {
    id: 'campus-ops',
    name: 'Campus Operations',
    category: 'Finance',
    icon: '🏛️',
    description: 'Rooms, assets, maintenance requests, events, transport and facility scheduling.',
    requiredModules: ['organization'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'enterprise',
  },
  {
    id: 'admissions',
    name: 'Admissions',
    category: 'Admissions',
    icon: '📝',
    description: 'Full lifecycle — lead capture, applications, interviews, offers and enrollment.',
    requiredModules: ['organization', 'finance', 'documents'],
    recommendedModules: ['students'],
    isCore: false,
    pricingTier: 'starter',
  },
  {
    id: 'curriculum',
    name: 'Curriculum Intelligence',
    category: 'Academics',
    icon: '📚',
    description: 'SLO mapping, learning outcomes, standards alignment and curriculum gap analysis.',
    requiredModules: ['organization'],
    recommendedModules: ['teaching'],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'syllabus',
    name: 'Syllabus Tracking',
    category: 'Academics',
    icon: '📊',
    description: 'Real-time coverage tracking per class, teacher and subject with AI-powered alerts.',
    requiredModules: ['organization', 'curriculum'],
    recommendedModules: ['teaching'],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'timetable',
    name: 'Timetable Intelligence',
    category: 'Academics',
    icon: '🗓️',
    description: 'Smart scheduling engine with conflict detection, substitution and room allocation.',
    requiredModules: ['organization'],
    recommendedModules: ['teaching', 'campus-ops'],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'library',
    name: 'Library',
    category: 'Academics',
    icon: '📖',
    description: 'Book catalog, member management, issue & return tracking, fines and digital resources.',
    requiredModules: ['organization', 'students'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'students',
    name: 'Student 360',
    category: 'Students',
    icon: '🧑‍🎓',
    description: 'Complete student profile — attendance, academic history, behaviour and family records.',
    requiredModules: ['organization'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'starter',
  },
  {
    id: 'assessment',
    name: 'Assessment & Results',
    category: 'Students',
    icon: '📝',
    description: 'Tests, marks, GPA, report cards, parent result access and class performance analytics.',
    requiredModules: ['organization', 'students', 'curriculum', 'teaching'],
    recommendedModules: ['syllabus'],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'behaviour',
    name: 'Behaviour & Tarbiyah',
    category: 'Students',
    icon: '🌱',
    description: 'PBIS-aligned behaviour tracking with Islamic character development (Tarbiyah) built in.',
    requiredModules: ['organization', 'students', 'teaching', 'documents'],
    recommendedModules: [],
    isCore: false,
    pricingTier: 'academic',
  },
  {
    id: 'analytics',
    name: 'Analytics & Intelligence',
    category: 'Intelligence',
    icon: '🤖',
    description: 'Claude AI-powered insights, predictive analytics, KPI dashboards and smart recommendations.',
    requiredModules: ['organization'],
    recommendedModules: ['documents'],
    isCore: false,
    pricingTier: 'enterprise',
  },
];

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULE_REGISTRY.find((m) => m.id === id);
}
